[Fix] 오류 사항 수정
wecode-bootcamp-korea/FreePorkBelly-backend pull request #10
Opened 2020-06-04 10:25 UTC by joey-younggap

[Fix] ProductView GET에서 product_id도 전달
- 이후 CartItem에 담길 때 활용하기 위해 product_id 사전에 전달

[Fix] 일부 주석 삭제 및 수정

2020-06-04 11:51 UTC, evergreen-david requested changes

2020-06-04 11:51 UTC, evergreen-david commented on order/views.py
> +            if Cart.objects.filter(customer_id=customer_id, cart_status_id=1).exists():
cart_status_id = 1 대신에 객체를 가져와서 외래키로 지정하거나 Enum 정의해서 처리하도록 수정하는게 좋을 것 같습니다. 
cart_status_id 와 order_status_id  주문완료 정보를 1,2,3 로 하면 나중에 유지보수 하지가 힘들기 때문에 수정을 부탁 드립니다.
예를 들어 1 -> PEDNING, 2-> PAID 3-> COMPLETE 이렇게 사용되는 클래스 또는 함수에서 정의해서 사용하도록 수정 부탁 드립니다.

2020-06-04 11:51 UTC, evergreen-david commented on order/views.py
> +                order_status_id     = 4,                           # 오더완료 시, status를 결제완료로 세팅
주문완료도 위에 커멘트 처럼 처리해 주세요!

2020-06-04 13:04 UTC, joey-younggap commented on order/views.py
> +                order_status_id     = 4,                           # 오더완료 시, status를 결제완료로 세팅
수정 하였습니다.

2020-06-04 13:04 UTC, joey-younggap commented on order/views.py
> +            if Cart.objects.filter(customer_id=customer_id, cart_status_id=1).exists():
수정하였습니다.

2020-06-05 02:14 UTC, evergreen-david approved these changes

2020-06-05 02:14 UTC, merged