add loginView
wecode-bootcamp-korea/FreePorkBelly-backend pull request #2
Opened 2020-05-28 13:04 UTC by eodyd6564

로그인, 회원가입 작성했습니다!

2020-05-29 02:07 UTC, evergreen-david requested changes

2020-05-29 02:07 UTC, evergreen-david commented on customer/models.py
> +    email    = models.CharField(max_length=50)
```suggestion
    email    = models.EmailField(max_length=50)
```

2020-05-29 02:07 UTC, evergreen-david commented on customer/models.py
> +        db_table = 'delivery_address'
```suggestion
        db_table = 'delivery_addresses'
```

2020-05-29 02:07 UTC, evergreen-david commented on customer/models.py
> +    created_at   = models.DateTimeField(auto_now_add=True)
생성일이랑 발행한 날짜랑 같은 정보로 볼수 있지않을까요? 유저에게 발행된 쿠폰일이면 CouponCustomer에 있어야할 것 같아요. 확인 부탁드립니다. 그리고 Column들은 중요한 순으로 만드는게 좋은데요 created_at 은 보통 column 마지막으로 쓰는게 좋을 것 같습니다.

2020-05-29 02:07 UTC, evergreen-david commented on customer/views.py
> +
불필요 공백 정리해주세요.

2020-05-29 02:07 UTC, evergreen-david commented on customer/views.py
> +                        token = jwt.encode({'email':data['email']},'SECRET',algorithm='HS256').decode('utf-8')
'SECRET', algorithm 정보 setting 에 가져와서 사용해주세요. 'SECRET' 키는 노출되면 안되는데 'SECRET'이라고 코드에 작성하면 노출되게 됩니다.

2020-05-29 07:17 UTC, eodyd6564 commented on customer/models.py
> +    created_at   = models.DateTimeField(auto_now_add=True)
넵

2020-05-29 07:17 UTC, eodyd6564 commented on customer/views.py
> +
넵

2020-05-30 07:37 UTC, joey-younggap commented on customer/views.py
> +
로그인, 회원가입 PR 새롭게 올렸습니다. 그러니, 이 PR은 삭제를 부탁 드립니다.

2020-06-01 11:05 UTC, closed without merging