Cart View 수정 / Main Page View 작성
wecode-bootcamp-korea/FreePorkBelly-backend pull request #8
Opened 2020-06-01 06:29 UTC by joey-younggap

[Add] Cart View 수정 / Main Page View 작성
- cart 추가하기, 보여주기 최종 테스트 후 완성본으로 업데이트
- main 화면에 보여질 products list view 작성

[Fix] Signup View 수정
- signup 시 존재하는 email의 경우 if문으로 예외처리로 변경

[Fix] 기타 상기 변동 사항 외 urls 등 변경

* REST url 법칙에 따른 url 변경은 오늘 발표 후 진행할 예정입니다.

2020-06-01 07:03 UTC, devops-andrew requested changes

2020-06-01 07:03 UTC, devops-andrew commented on customer/views.py
> +                return JsonResponse({'message':'Already registered email'}, status=400)
이 메세지는 프론트에서 활용하나요? 메세지코드 컨벤션이 제각각입니다. 확인해주세요.
```suggestion
                return JsonResponse({'message':'EMAIL_ALREADY_EXIST'}, status=400)
```

2020-06-01 07:03 UTC, devops-andrew commented on customer/views.py
>              return JsonResponse({'message':'INVALID INPUT'}, status=400)
TypeError를 만나기보다 만나기 전에 미리 검사하는게 더 좋을것 같네요.

2020-06-01 07:03 UTC, devops-andrew commented on freeporkbelly_main/urls.py
>      #path('support', include('support.urls'))
사용안하는 코드는 제거해주세요.

2020-06-01 07:03 UTC, ulfrid commented on product/views.py
> +        products = Product.objects.all()[0:6]    # 프로덕트 중에서 6개만 뽑음
리미트 값을 준다면 하드코딩이 아니라 
PRODUCT_MAIN_LIMIT = 6
과 같이 상수로 지정하고 처리하는게 가독성에 좋습니다.
```suggestion
        products = Product.objects.all()[:PRODUCT_MAIN_LIMIT]    # 프로덕트 중에서 6개만 뽑음
```

2020-06-01 10:59 UTC, joey-younggap commented on customer/views.py
> +                return JsonResponse({'message':'Already registered email'}, status=400)
수정 사항 반영하였습니다.

2020-06-01 10:59 UTC, joey-younggap commented on customer/views.py
>              return JsonResponse({'message':'INVALID INPUT'}, status=400)
수정 사항 반영하였습니다.

2020-06-01 10:59 UTC, joey-younggap commented on freeporkbelly_main/urls.py
>      #path('support', include('support.urls'))
수정 사항 반영하였습니다.

2020-06-01 10:59 UTC, joey-younggap commented on product/views.py
> +        products = Product.objects.all()[0:6]    # 프로덕트 중에서 6개만 뽑음
수정 사항 반영하였습니다.

2020-06-01 11:02 UTC, joey-younggap commented
피드백 사항 반영하여, 수정하여 다시 푸시 날렸습니다.
아울러 피드백 사항 외에 Cart View에서 
- post : 유저가 맨 처음 카트아이템을 추가할 때 카트를 신규로 생성하는 로직 추가
  (맨 처음 카트아이템을 추가할 때 발생했던 오류 해결)
- delete : 오타 수정 (테스트 완료)

2020-06-02 01:45 UTC, soheon-lee commented on order/views.py
> +                cart = Cart.objects.filter(customer_id=data['customer_id']).last()
.get 메소드를 사용하지 않고, filter().last()를 하시는 이유가 있을까요?

2020-06-02 01:49 UTC, soheon-lee commented on order/views.py
> +                cart = Cart.objects.filter(customer_id=data['customer_id']).last()
get() 메소드를 사용하지 않고, filter().last()를 사용하시는 이유 설명 부탁드립니다.

2020-06-02 01:52 UTC, soheon-lee commented on order/views.py
>                  'quantity' : cart_item.quantity
cart_item에서 바로 name에 접근 하실 수 있습니다. 로직 수정부탁드립니다.

2020-06-02 01:53 UTC, soheon-lee commented on product/views.py
> +        PRODUCT_MAIN_LIMIT = 6                   # 메인페이지에 6개 상품만 보여줌
숫자 6은 프론트엔드에서 쿼리스트링으로 받아주세요

2020-06-02 11:19 UTC, joey-younggap commented on order/views.py
> +                cart = Cart.objects.filter(customer_id=data['customer_id']).last()
이 부분은 아까 전에 말씀 나눠서 설명 드렸습니다.

2020-06-02 11:19 UTC, joey-younggap commented on order/views.py
>                  'quantity' : cart_item.quantity
오~ 감사합니다. 방금 전 로직 수정했습니다.

2020-06-02 11:20 UTC, joey-younggap commented on product/views.py
> +        PRODUCT_MAIN_LIMIT = 6                   # 메인페이지에 6개 상품만 보여줌
프론트엔드에서 쿼리스트링으로 받아오도록 로직 수정했습니다.
다만, 없을 경우 기본값을 6으로 하였습니다.

2020-06-03 06:35 UTC, soheon-lee commented
LGTM

2020-06-03 06:35 UTC, merged